export const BINARY_GLTF_MODEL_EXTENSION = '.glb'
export const SEPARATE_GLTF_MODEL_EXTENSION = '.gltf'

export const GLTF_MODEL_EXTENSIONS = [BINARY_GLTF_MODEL_EXTENSION, SEPARATE_GLTF_MODEL_EXTENSION]
