name: ci

permissions:
  contents: read

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev
  workflow_dispatch: {}

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: set node version & pnpm cache
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: pnpm

      - run: corepack enable

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Test lint
        run: pnpm run lint
