name: Release Creation on GitHub & NPM Publishing

on:
  push:
    branches:
      - main
  workflow_dispatch: {}

jobs:
  check_conditions:
    name: Check conditions to create & release
    runs-on: ubuntu-latest
    permissions:
      contents: read
    outputs:
      do_release: ${{ steps.check_create_release_suffix.outputs.do_release }}
      do_release_changelog_generation: ${{ steps.check_create_release_suffix.outputs.do_release_changelog_generation }}
      do_release_version_bump: ${{ steps.check_create_release_suffix.outputs.do_release_version_bump }}
      do_release_version_bump_force_version: ${{ steps.check_create_release_suffix.outputs.do_release_version_bump_force_version }}
    steps:
      - name: Checkout the Codebase
        uses: actions/checkout@v4
        with:
          ref: main # branch to checkout
          fetch-depth: 0

      - name: Check first line of commit message and search for commands `[rel-TYPE-CHANGELOG]`
        id: check_create_release_suffix
        uses: actions/github-script@v7
        with:
          script: |
            // context.sha === context.payload.head_commit.id

            // Get first line of last commit message
            const lastCommitMessage = context.payload.head_commit.message;
            const lastCommitMessageFirstLine = lastCommitMessage.split('\n')[0];

            let do_release = "false";
            let do_release_version_bump = "false";
            let do_release_version_bump_force_version = "";
            let do_release_changelog_generation = "false";

            const allowedTypes = [
              "none",
              // --------
              "auto",
              // --------
              "major",
              "minor",
              "patch",
              "premajor",
              "preminor",
              "prepatch",
              "prerelease",
            ];

            const allowedChangelog = [
              "y",
              "n",
            ];

            const regex = /\[rel-([a-z]+)-([a-z]+)\]/;
            const match = lastCommitMessageFirstLine.match(regex);

            if (match) {
              do_release = "true";

              const cmdType = match[1];
              const cmdChangelog = match[2];

              if(!allowedTypes.includes(cmdType)){
                throw new Error(`Invalid release TYPE: ${cmdType}`);
              }
              if(!allowedChangelog.includes(cmdChangelog)){
                throw new Error(`Invalid release CHANGELOG: ${cmdChangelog}`);
              }

              if(cmdType !== "none"){
                do_release_version_bump = "true";
                if(cmdType !== "auto"){
                  do_release_version_bump_force_version = `--${cmdType}`;
                }
              }

              if(cmdChangelog === "y"){
                do_release_changelog_generation = "true";
              }
            }

            console.dir(`Set output: do_release=${do_release}`);
            core.setOutput("do_release", do_release);

            console.dir(`Set output: do_release_version_bump=${do_release_version_bump}`);
            core.setOutput("do_release_version_bump", do_release_version_bump);

            console.dir(`Set output: do_release_version_bump_force_version=${do_release_version_bump_force_version}`);
            core.setOutput("do_release_version_bump_force_version", do_release_version_bump_force_version);

            console.dir(`Set output: do_release_changelog_generation=${do_release_changelog_generation}`);
            core.setOutput("do_release_changelog_generation", do_release_changelog_generation);

  dependence-lint:
    name: Depend on Lint
    uses: ./.github/workflows/lint.yml

  create_release:
    needs:
      - check_conditions
      - dependence-lint
    if: needs.check_conditions.outputs.do_release == 'true'
    name: Create GitHub Release & NPM Publish
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout the Codebase
        uses: actions/checkout@v4
        with:
          ref: main # branch to checkout
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Enable pnpm
        run: |
          corepack enable
          corepack prepare pnpm@v9.15.4 --activate

      - name: Init git config for the bot by setting name & email
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "no-reply@todde.tv"

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      # - name: Get old `package.json` version
      #   id: get_package_version_old
      #   run: echo version=$(node -p "require('./package.json').version") >> $GITHUB_OUTPUT

      - name: Bump `package.json` version depending on given TYPE from commit message
        if: needs.check_conditions.outputs.do_release_version_bump == 'true'
        # -from "v${{ steps.get_package_version_old.outputs.version }}"
        run: pnpm changelogen --bump ${{ needs.check_conditions.outputs.do_release_version_bump_force_version }} --no-commit --no-tag
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

      - name: Get new `package.json` version
        id: get_package_version_new
        run: echo version=$(node -p "require('./package.json').version") >> $GITHUB_OUTPUT

      - name: Generate changelog from conventional commits
        if: needs.check_conditions.outputs.do_release_changelog_generation == 'true'
        # -from "v${{ steps.get_package_version_old.outputs.version }}"
        run: pnpm changelogen --output CHANGELOG.md -r "${{ steps.get_package_version_new.outputs.version }}" --no-commit --no-tag
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

      - name: Git add, commit & push changes made to `main` (potentially `package.json` & `CHANGELOG.md`)
        if: needs.check_conditions.outputs.do_release_version_bump == 'true' || needs.check_conditions.outputs.do_release_changelog_generation == 'true'
        run: |
          git add .
          git commit -m "chore(release): v${{ steps.get_package_version_new.outputs.version }}"
          git push origin main

      - name: Create a tag
        run: |
          git tag -a "v${{ steps.get_package_version_new.outputs.version }}" -m "Release v${{ steps.get_package_version_new.outputs.version }}"
          git push origin --tags

      - name: Sync tags with GitHub releases & create the new release
        # run: pnpm changelogen gh release all
        run: pnpm changelogen gh release "v${{ steps.get_package_version_new.outputs.version }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # - name: Install dependencies
      #   run: pnpm install --frozen-lockfile

      - name: Build the project
        run: pnpm run build

      # - name: Publish package to NPM
      #   if: github.ref == 'refs/heads/main'
      #   run: pnpm publish --access public
      #   env:
      #     NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Publish package to NPM
        # if: github.ref == 'refs/heads/main'
        uses: JS-DevTools/npm-publish@v3
        with:
          token: ${{ secrets.NPM_TOKEN }}
          access: public
          # registry: "https://npm.pkg.github.com/"
          registry: https://registry.npmjs.org/
