name: Linting

on:
  pull_request:
    branches:
      - main
  workflow_dispatch: {}
  workflow_call: {}

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout the Codebase
        uses: actions/checkout@v4

      - name: Setup pnpm as package manager
        uses: pnpm/action-setup@v3
        with:
          version: 9.15.4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: pnpm

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Test lint
        run: pnpm run lint
