name: Test

on:
  pull_request:
    branches:
      - main
  workflow_dispatch: {}
  workflow_call: {}

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout the Codebase
        uses: actions/checkout@v4

      - name: Get last commit message
        uses: actions/github-script@v7
        with:
          script: |
            const commit = await github.rest.repos.getCommit({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: context.sha
            });
            console.dir(commit.data.commit.message);
            console.dir(commit);
            console.dir(context.sha);
            console.dir(context);
